name: GitHub Actions Publish
run-name: ${{ github.actor }} Running yarn buid 🚀
on: [push]
jobs:
  Explore-GitHub-Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: workspaces run build:prod # will run `yarn workspaces run build:prod` command

      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: workspaces run test # will run `yarn workspaces run test` command